wandb_version: 1

H:
  desc: null
  value: 84
W:
  desc: null
  value: 84
_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1656610998
    t:
      1:
      - 1
      - 55
      - 79
      2:
      - 1
      - 55
      - 79
      3:
      - 15
      4: 3.6.8
      5: 0.12.18
      8:
      - 5
batch-size:
  desc: null
  value: 32
env:
  desc: null
  value: PongNoFrameskip-v4
lr:
  desc: null
  value: 0.0001
max_grad_norm:
  desc: null
  value: 5.0
num_frames:
  desc: null
  value: 2
seed:
  desc: null
  value: 42
steps:
  desc: null
  value: 250000
