wandb_version: 1

K:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1656010460
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 15
      4: 3.6.8
      5: 0.12.18
      8:
      - 5
batch-size:
  desc: null
  value: 64
env:
  desc: null
  value: MsPacmanNoFrameskip-v4
image-channels:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
lr-decay:
  desc: null
  value: 0.95
lr-decay-len:
  desc: null
  value: 100000.0
max_ep_len:
  desc: null
  value: 100
num_eps:
  desc: null
  value: 100
steps:
  desc: null
  value: 1000000.0
