wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1657232406
    t:
      1:
      - 1
      - 55
      - 79
      2:
      - 1
      - 55
      - 79
      3:
      - 15
      4: 3.6.8
      5: 0.12.18
      8:
      - 5
batch-size:
  desc: null
  value: 32
env:
  desc: null
  value: PongNoFrameskip-v4
image-channels:
  desc: null
  value: 3
image-size:
  desc: null
  value:
  - 256
  - 256
lr:
  desc: null
  value: 0.0001
max_ep_len:
  desc: null
  value: 100
num_eps:
  desc: null
  value: 1000
steps:
  desc: null
  value: 10000
weight-decay:
  desc: null
  value: 0.0001
